WITH PARENT_02 AS (SELECT ECOLI_DATA.ID AS ID
                    FROM ECOLI_DATA 
                    INNER JOIN (SELECT ID
                                    FROM ECOLI_DATA 
                                    WHERE PARENT_ID IS NULL) AS PARENT_01
                    ON PARENT_01.ID = ECOLI_DATA.PARENT_ID)
     

SELECT ECOLI_DATA.ID
FROM ECOLI_DATA 
INNER JOIN PARENT_02
ON PARENT_02.ID = ECOLI_DATA.PARENT_ID
ORDER BY ECOLI_DATA.ID ASC
;