-- 코드를 작성해주세요
SELECT ID, 
    CASE
        WHEN B.CNT_PATENT_ID IS NULL THEN 0
        ELSE B.CNT_PATENT_ID
    END AS CHILD_COUNT
FROM ECOLI_DATA 
LEFT JOIN (SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT_PATENT_ID
        FROM ECOLI_DATA 
        GROUP BY PARENT_ID) AS B
ON ECOLI_DATA.ID = B.PARENT_ID
ORDER BY 1
;