-- 코드를 작성해주세요
SELECT SUM(HR_GRADE.SCORE) SCORE, HR_EMPLOYEES.EMP_NO, HR_EMPLOYEES.EMP_NAME, HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL
FROM HR_EMPLOYEES 
INNER JOIN HR_DEPARTMENT
ON HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
INNER JOIN HR_GRADE 
ON HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
WHERE HR_GRADE.YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1
;