-- 코드를 작성해주세요
SELECT YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) AS YEAR, (MAX_YEAR.SIZE-ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV, ECOLI_DATA.ID
FROM ECOLI_DATA
LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
            FROM ECOLI_DATA
            GROUP BY YEAR(DIFFERENTIATION_DATE)) AS MAX_YEAR
ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MAX_YEAR.YEAR
ORDER BY YEAR, YEAR_DEV ASC
;