-- 코드를 입력하세요
WITH A AS (
SELECT WRITER_ID, COUNT(WRITER_ID) AS CNT
FROM USED_GOODS_BOARD 
GROUP BY WRITER_ID
HAVING CNT >= 3
)

SELECT USED_GOODS_USER.USER_ID, NICKNAME, CONCAT(CITY, " ",STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTR(TLNO, 1, 3), "-", SUBSTR(TLNO, 4, 4), "-", SUBSTR(TLNO, 8, 4)) AS 전화번호
FROM A
LEFT JOIN USED_GOODS_USER
ON USED_GOODS_USER.USER_ID = A.WRITER_ID
ORDER BY USED_GOODS_USER.USER_ID DESC
;