-- 코드를 작성해주세요
SELECT ECOLI_DATA.ID, ECOLI_DATA.GENOTYPE, PARENT_DATA.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA
INNER JOIN (SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, ECOLI_DATA.GENOTYPE
            FROM ECOLI_DATA ) AS PARENT_DATA
ON ECOLI_DATA.PARENT_ID = PARENT_DATA.ID
WHERE PARENT_DATA.GENOTYPE & ECOLI_DATA.GENOTYPE = PARENT_DATA.GENOTYPE
ORDER BY ECOLI_DATA.ID

;