-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(SUM(R.REVIEW_SCORE)/COUNT(R.REST_ID), 2) AS AVERAGE_REVIEW_SCORE
FROM REST_INFO AS I
INNER JOIN REST_REVIEW AS R
ON R.REST_ID = I.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY AVERAGE_REVIEW_SCORE DESC, FAVORITES DESC
;