WITH UI AS (SELECT *
            FROM USER_INFO 
            WHERE YEAR(JOINED) = '2021')

SELECT YEAR(OS.SALES_DATE) YEAR
        , MONTH(OS.SALES_DATE) MONTH
        , COUNT(DISTINCT UI.USER_ID) PUCHASED_USERS
        , ROUND(COUNT(DISTINCT UI.USER_ID)/(SELECT COUNT(DISTINCT USER_ID)
                                            FROM USER_INFO
                                            WHERE YEAR(JOINED) = '2021'), 1) PUCHASED_RATIO
FROM ONLINE_SALE OS
LEFT JOIN UI 
ON OS.USER_ID = UI.USER_ID
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
;

