-- 코드를 작성해주세요
# SELECT ITEM_TREE.ITEM_ID, ITEM_INFO.ITEM_NAME
# FROM ITEM_TREE 
# LEFT JOIN ITEM_INFO 
# ON ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID
# WHERE ITEM_TREE.PARENT_ITEM_ID IS NULL
# ;

SELECT II.ITEM_ID, II.ITEM_NAME
FROM ITEM_INFO II
LEFT JOIN ITEM_TREE IT
ON II.ITEM_ID = IT.ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
;