WITH RECURSIVE PARENT_TREE AS (
SELECT ID, PARENT_ID, 1 AS LEVEL
FROM ECOLI_DATA 
WHERE PARENT_ID IS NULL

UNION ALL

SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, 1+PARENT_TREE.LEVEL AS LEVEL
FROM ECOLI_DATA
INNER JOIN PARENT_TREE
ON PARENT_TREE.ID = ECOLI_DATA.PARENT_ID
)

SELECT COUNT(LEVEL) AS COUNT, LEVEL AS GENERATION
FROM PARENT_TREE
LEFT OUTER JOIN (
            SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT
            FROM PARENT_TREE
            GROUP BY LEVEL, PARENT_ID) AS CNT_PARENT
ON CNT_PARENT.PARENT_ID = PARENT_TREE.ID
WHERE CNT_PARENT.PARENT_ID IS NULL
GROUP BY LEVEL
ORDER BY GENERATION
;