# -- 코드를 입력하세요
WITH BA AS (SELECT BOOK_ID, B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, PRICE
                FROM BOOK AS B
                LEFT JOIN AUTHOR AS A
                ON B.AUTHOR_ID = A.AUTHOR_ID)

SELECT BA.AUTHOR_ID, BA.AUTHOR_NAME, BA.CATEGORY, SUM(BS.SALES*BA.PRICE) AS SALES
FROM (SELECT *
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') AS BS
INNER JOIN BA
ON BA.BOOK_ID = BS.BOOK_ID
GROUP BY BA.AUTHOR_ID, BA.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC

;