WITH PERCENT_TABLE AS (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
FROM ECOLI_DATA)

SELECT ECOLI_DATA.ID,
CASE 
    WHEN PERCENT_TABLE.PERCENT <= 0.25 THEN 'CRITICAL'
    WHEN PERCENT_TABLE.PERCENT <= 0.5 THEN 'HIGH'
    WHEN PERCENT_TABLE.PERCENT <= 0.75 THEN 'MEDIUM' 
    ELSE 'LOW'
END AS COLONY_NAME
FROM ECOLI_DATA
LEFT JOIN PERCENT_TABLE
ON PERCENT_TABLE.ID = ECOLI_DATA.ID
ORDER BY ECOLI_DATA.ID 
;