# WITH A AS (SELECT *
#             FROM USED_GOODS_BOARD
#             WHERE STATUS = 'DONE')

# WITH B AS (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
#             FROM A 
#             GROUP BY WRITER_ID
#             HAVING TOTAL_SALES >= 700000)
            
WITH B AS (
        SELECT A.WRITER_ID, SUM(PRICE) AS TOTAL_SALES
        FROM (
            SELECT *
            FROM USED_GOODS_BOARD
            WHERE STATUS = 'DONE'
            ) AS A
        GROUP BY WRITER_ID
        HAVING TOTAL_SALES >= 700000 
    )

SELECT USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, B.TOTAL_SALES
FROM B
LEFT JOIN USED_GOODS_USER 
ON USED_GOODS_USER.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES ASC
;