-- 코드를 입력하세요
WITH A AS (
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME, ANIMAL_INS.DATETIME AS INS_DATE, ANIMAL_OUTS.DATETIME AS OUTS_DATE
FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
    )
    
SELECT ANIMAL_ID, NAME
FROM A
WHERE INS_DATE > OUTS_DATE
ORDER BY INS_DATE ASC
;
