WITH TOTAL AS (SELECT HISTORY_ID, DATEDIFF(END_DATE, START_DATE)+1 DURATION,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE)+1>= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE)+1>= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE)+1>= 7 THEN '7일 이상'
        ELSE 'NULL'
    END DURATION_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CCRH
INNER JOIN CAR_RENTAL_COMPANY_CAR CRCC
ON CCRH.CAR_ID = CRCC.CAR_ID
WHERE CRCC.CAR_TYPE = '트럭')

SELECT HISTORY_ID, 
    CASE
        WHEN CRCD.DISCOUNT_RATE IS NOT NULL THEN ROUND(DURATION*(TOTAL.DAILY_FEE*(100-CRCD.DISCOUNT_RATE)/100))
        ELSE DURATION*TOTAL.DAILY_FEE
    END FEE
FROM TOTAL
LEFT JOIN (SELECT *
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = '트럭') CRCD
ON TOTAL.DURATION_TYPE = CRCD.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC
;